services:
  application:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    image: application
    container_name: application
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel_app
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_app
  db:
    container_name: mp_mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'cashflow'
    volumes:
      - dbdata:/var/lib/mysql/
      - ./dockerfiles/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel_app
networks:
  laravel_app:
    driver: bridge
    
volumes:
    dbdata:
        driver: local